name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          VITE_BASE: /precision-drywall-design/

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout --orphan gh-pages
          git reset --hard
          rm -rf *
          cp -r dist/* .
          git add .
          git commit -m "Deploy website"
          git push origin gh-pages --force