name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          VITE_BASE: /precision-drywall-design/

      - name: List Workspace Contents
        run: ls -al

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout --orphan gh-pages
          
          mkdir -p temp_deploy
          cp -r ./dist/* temp_deploy/
          ls -al
          # Remove all files and directories in the current working directory (gh-pages)
          find . -maxdepth 1 -not -name 'temp_deploy' -not -name '.' -not name '.git' -exec rm -rf {} +
          # Copy the built site from the temporary directory to the root of gh-pages
          ls -al
          cp -r temp_deploy/* .
          # Remove the temporary directory
          ls -al
          rm -rf temp_deploy
          git add --all .
          git commit -m "Deploy website"
          git push origin gh-pages --force